import "./globals.css";
import { Inter, Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-ubuntu",
});

const inter = Inter({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const classNames = ` ${inter.variable} ${ubuntu.variable}`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames}>{children}</body>
    </html>
  );
}
